server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/room_go_db
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        cache:
          use_second_level_cache: false
          region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
    show-sql: false
    hibernate:
      ddl-auto: none

  sendGrid:
    apiKey: ${SENDGRID_API_KEY:dummy_key_for_dev_env}
    fromEmail: ${SENDGRID_FROM_EMAIL:email@example.com}
    templateId: ${SENDGRID_TEMPLATE_ID:d-2116466afd0a438b90615184dd569e42}
    verificationLink: ${SENDGRID_VERIFICATION_LINK:http://esb-camel:8080/api/auth/verify-email?token=}

services:
  esb:
    url: ${ESB_URL:http://esb-camel:8080/api/esb}


# application-dev.yml
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: backend-service
    server: ${BACKEND_HOST:http://localhost:${server.port}}
    title: User Service
    version: 1.0.0

jwt:
  expiryMinutes: ${JWT_EXPIRY_MINUTES:60}
  expiryDay: ${JWT_EXPIRY_DAY:14}
  accessKey: ${JWT_ACCESS_KEY:IIwLeRIVsznVTPFEYmA6HiVVBrlKkKqC36OpWzqw8mk=}
  refreshKey: ${JWT_REFRESH_KEY:tvszknimPZQEdy3c9TCERBLAkOyoCc2ZvOmGcHsRJgg=}